dist: focal
os: linux
addons:
  apt:
    update: true
    packages:
    - libgsl-dev
language: python
python:
  - "3.8"
  - "3.9"
install:
- export TRAVIS_TAG=$(git tag --points-at HEAD)
- echo $TRAVIS_TAG
- cd $TRAVIS_BUILD_DIR
- pip install .
- pip list
script:
- cd $HOME
- python -c "import pygad"
- python -c "import pygad,doctest,sys; res = doctest.testmod(pygad); sys.exit(res.failed)"
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  username: "mihac"
  edge: true
  distributions: "sdist"
  skip_existing: true
  on:
    tags: true 
