# This is a build configuration.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: broett/std_programming_env
  username: broett
  password: $PWD_SECURE
  email: broett@mpa-garching.mpg.de

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - python setup.py install
          - python -c "import pygad; print pygad.version"
